services:
  grafana:
    image: grafana/grafana:11.1.4-ubuntu
    container_name: grafana
    restart: unless-stopped
    user: '0'
    ports:
      - '3000:3000'
    volumes:
      - 'grafana-storage:/var/lib/grafana'
      - '$PWD/grafana/grafana.ini:/etc/grafana/grafana.ini'

  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: prometheus
    restart: unless-stopped
    user: '0'
    ports:
      - '9090:9090'
    volumes:
      - '$PWD/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prometheus-storage:/prometheus'

  uptime-kuma:
    image: louislam/uptime-kuma:1.23.13
    container_name: uptime-kuma
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - 'uptime-kuma-storage:/app/data'

volumes:
  grafana-storage: {}
  prometheus-storage: {}
  uptime-kuma-storage: {}
